local GameResources = {
    ["Foods"] = {
        ["CanBePurchased"] = {
            "OatMuffin",
            "SugarMuffin",
            "MintMuffin",
            "CarrotMuffin",
            "AppleMuffin"
        },
        ["Others"] = {
            "Apple",
            "Pansies",
            "Mints",
            "Daylilies",
            "SugarCubes",
            "HayCubes",
            "Carrot",
            "Peppermint",
            "GreenApple",
            "AlfalfaCubes",
            "Strawberry",
            "WhiteCarrot",
            "VibrantDaylilies",
            "Candycanes",
            "PinkPrincessApple",
            "BrightPansies",
            "Pineberry",
            "Peach",
            "OatTreats",
            "Meadowsweet",
            "ChocolateCookie",
            "WhitePeach",
            "GoldApple",
            "PurpleCarrot",
            "Fawnberry",
            "Helianthus",
            "PeppermintCookie",
            "BirthdayCake",
            "BasicFeed",
            "GoodFeed",
            "PremiumFeed",
            "ExclusiveFeed",
            "MysticFeed",
            "BasicJam",
            "SweetJam",
            "LushJam",
            "RichJam",
            "EtherealJam",
            "RawHoney",
            "AmberHoney",
            "SunHoney",
            "RoyalHoney",
            "CelestialHoney",
            "MagicMuffins"
        }
    },
    ["Lassos"] = {
        ["CanBePurchased"] = {
            "TornLasso",
            "StringLasso",
            "WovenLasso",
            "RopeLasso",
            "WesternLasso",
            "BrightLasso",
            "VibrantLasso",
            "WeakMagicLasso",
            "MagicalLasso",
            "StoneLasso",
            "OvergrownLasso",
            "KelpLasso",
            "CloudLasso",
            "MysticCloudLasso",
            "WebLasso",
            "MysticWebLasso",
            "FlowerLasso",
            "RoseLasso",
            "CactiLasso",
            "WaterLasso",
            "OceanLasso",
        },
        ["Others"] = {
            "RainbowLasso",
            "GoldLasso",
            "BraidedLasso",
            "CakeLasso",
            "RedVelvetLasso",
            "GhostLasso",
            "UndeadLasso",
            "SnowLasso",
            "IceLasso",
            "MasterLasso",
            "SpringLasso",
            "BunnyLasso",
            "SillyLasso",
        }
    },
    ["Species"] = {
        "Horse",
        "Cactaline",
        "Pony",
        "Equus",
        "Bisorse",
        "Caprine",
        "Unicorn",
        "Gargoyle",
        "Kelpie",
        "Peryton",
        "Fae",
        "Flora",
        "Plush",
        "Cybred",
        "Saurequine",
        "Hippocampus",
        "Ghoulsteed",
        "Celestial",
        "Kirin"
    },
    ["Nodes"] = {
        ["Food"] = {
            "AppleBarrel", 
            "BerryBush", 
            "CatctusFruit", 
            "FoodPallet", 
            "LargeBerryBush", 
            "Stump",
            "SilkBush"
        },
        ["Resource"] = {
            "StoneDeposit",
            "FallenTree"
        },
        ["Treasure"] = {
            "Treasure"
        }
    },
    ["Resources"] = {},
    ["Potions"] = {},
    ["Seeds"]  = {}
}

return GameResources
